### ISSUE TITLE
Print inventory error

### ISSUE THREAD

**Issue by ryan-turner** [chandlerbaggett/Baggett_CSCI2270_FinalProject#4]
When the user rents a movie, and then returns it, the returned movie still appears in the users inventory.

Steps to reproduce:
Enter: 2
Title: Casablanca
Enter: 8
Title: Casablanca
Enter: 9
Result: Casablanca is still in user inventory after being returned.

**Comment by pikawolfy** [comment]
I also encountered this issue with Fight Club.
